clean:
	rm -f *.sta *.out *.12d *.cvg *.dat *.fcv
	rm -f *.eig *.nam input*  abc tmp* error*
	rm -f *.equ *.rout *.net *.fbd *.stm *.mtx
	rm -f *.dof *.sti *.rin *.vwf *.str *.mas
	find . -name "*.frd" -not -name "beamfrdwrite.frd" -not -name "masterhcf.frd" -not -name "masterII.frd" -not -name "twobeam.frd" -exec rm -f {} +